export const PortData = {
  graphicalEffects: {
    graphHeight: "100%",
    graphWidth: "100%",
    graphLeft: 0,
    graphRight: 0,
    positioning: "0",
    title: "Apple",
    ticker: "AAPL",
    fontSize: 18,
    backgroundColor: "white",
    lineWidth: 5,
    boundaryWidth: 3,
    gainColor: "green",
    lossColor: "red",
    fillColor: "red",
    dateRangeActive: false,
    graphFontSize: 14,
    infoDivWidth: 100,
    buttonSize: { width: 40, height: 25 },
    buttonFontSize: 10,
    buttonColor: "grey",
    buttonFontColor: "black",
    buttonBorder: "1px solid red",
    contentsDiv: "portfolio_graph_render",
  },
};
